src/LarkinDeliverySystem/config/routes.rb
Rails.application.routes.draw do
  get 'trucks/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/orders/upload', to: 'orders#upload_view'
  post '/orders/upload', to: 'orders#upload'
  resources :orders, only: [:index, :show, :upload_view, :upload] do
    put '/order_deliveries/:id', to: 'order_deliveries#split'
    resources :order_deliveries, only: [:edit, :update] # знаю, знаю стоило OrderDelivery - назвать просто Delivery
  end

  get '/trips/my', to: 'trips#index_my'
  get '/trips/:id/txt', to: 'trips#export_to_txt', as: 'trip_txt'
  get '/trips/:id/pdf', to: 'trips#export_to_pdf', as: 'trip_pdf'
  resources :trips do
    put :cargo, to: 'trip_cargo#update'
    delete :cargo, to: 'trip_cargo#destroy'
    resources :cargo, :controller => :trip_cargo, only: [:create] # знаю, знаю стоило TripCargo - назвать просто Cargo
  end

  resources :trucks, only: [:index]

  devise_for :users

  root 'welcome#index'
end

src/LarkinDeliverySystem/app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :time_shift, :class_name => 'DeliveryShift', :foreign_key => 'time_shift_code', :validate => true
  belongs_to :truck
  belongs_to :driver, :class_name => 'User', :foreign_key => 'driver_id', :validate => true
  has_many :cargo, :class_name => 'TripCargo'

  def check_volume(notices, new_deliveries = nil)
    cargo_items = self.cargo.
        joins(order_delivery: [{order: [:origin_address, :destination_address]}]).
        #select(order_delivery: [:volume, order: [:number, origin_address: :name, destination_address: :name]]).
        select('trip_cargos.id, trip_cargos.order_delivery_id, order_deliveries.id, order_deliveries.volume,
 order_deliveries.order_id, orders.id, orders.number, orders.origin_address_id, addresses.name, orders.destination_address_id, destination_addresses_orders.name').
        order :order_num

    is_error = false
    max_cubes = self.truck.max_cubes
    volume_loaded_on_stock = 0

    cargo_items.each { |c|
      is_from_stock_to_client = Address.address_stock_names.include?(c.order_delivery.order.origin_address.name) # доставка
      is_from_client_to_stock = Address.address_stock_names.include?(c.order_delivery.order.destination_address.name) # возврат

      if !is_from_stock_to_client && !is_from_client_to_stock
        notices.warning "У заказа #{c.order_delivery.order.number} в адресах не указан склад, по этому он будет считаться доставкой клиенту (а не возвратом)"
      end

      volume_loaded_on_stock += c.order_delivery.volume unless is_from_client_to_stock
      if max_cubes < volume_loaded_on_stock
        is_error = true
        notices.error "Заказ #{c.order_delivery.order.number} с объемом #{c.order_delivery.volume}ft3 не помещается, превыщен объем (#{volume_loaded_on_stock}ft3/#{max_cubes}ft3)"
      end
    }

    if new_deliveries
      new_deliveries.each { |d|
        is_from_stock_to_client = Address.address_stock_names.include?(d.order.origin_address.name) # доставка
        is_from_client_to_stock = Address.address_stock_names.include?(d.order.destination_address.name) # возврат

        if !is_from_stock_to_client && !is_from_client_to_stock
          notices.warning "У заказа #{d.order.number} в адресах не указан склад, по этому он будет считаться доставкой клиенту (а не возвратом)"
        end

        volume_loaded_on_stock += d.volume unless is_from_client_to_stock
        if max_cubes < volume_loaded_on_stock
          is_error = true
          notices.error "Заказ #{d.order.number} с объемом #{d.volume}ft3 не помещается, превыщен объем (#{volume_loaded_on_stock}ft3/#{max_cubes}ft3)"
        end
      }
    end

    volume_current = volume_loaded_on_stock

    cargo_items.each { |c|
      is_from_client_to_stock = Address.address_stock_names.include?(c.order_delivery.order.destination_address.name) # возврат

      volume_current -= c.order_delivery.volume unless is_from_client_to_stock
      if is_from_client_to_stock
        volume_current += c.order_delivery.volume

        if max_cubes < volume_current
          is_error = true
          notices.error "Заказ #{c.order_delivery.order.number} на возврат с объемом #{c.order_delivery.volume}ft3 не помещается (предварительно необходимо сделать доставку) (#{volume_current}/#{max_cubes})"
        end
      end
    }

    if new_deliveries
      new_deliveries.each { |d|
        is_from_client_to_stock = Address.address_stock_names.include?(d.order.destination_address.name) # возврат

        volume_current -= d.volume unless is_from_client_to_stock
        if is_from_client_to_stock
          volume_current += d.volume

          if max_cubes < volume_current
            is_error = true
            notices.error "Заказ #{d.order.number} на возврат с объемом #{d.volume}ft3 не помещается (предварительно необходимо сделать доставку) (#{volume_current}/#{max_cubes})"
          end
        end
      }
    end

    return is_error
  end

  def volumes(re_calculate = false)
    @volumes ||= nil
    return @volumes if @volumes && !re_calculate

    sums = cargo.all.
        joins(order_delivery: [{order: [:origin_address, :destination_address]}]).
        select("case
when destination_addresses_orders.name in (#{Address.address_stock_names_to_s_sql}) then 1
else 0 end as is_from_client_to_stock,
sum(order_deliveries.volume) as s").
        group('is_from_client_to_stock').
        order('is_from_client_to_stock')

    is_from_stock_to_client = 0
    is_from_client_to_stock = 0
    sums.each do |r|
      is_from_stock_to_client = r[:s] if r[:is_from_client_to_stock] == 0
      is_from_client_to_stock = r[:s] if r[:is_from_client_to_stock] == 1
    end

    return @volumes = {is_from_stock_to_client: is_from_stock_to_client, is_from_client_to_stock: is_from_client_to_stock}
  end
end

src/LarkinDeliverySystem/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  SORT = {}

  before_filter :authenticate_user!

  load_and_authorize_resource

  def index(for_driver = nil)
    @build_path = lambda { |p| pp = p.permit(:p, s: [:f, :d], f: [:utf8, :search, :date, :commit]); for_driver == :for_driver ? trips_my_path(pp) : trips_path(pp) }

    @pagination = Pagination.new(params, :p, 10, 20, &@build_path)

    query = Trip.includes(:time_shift, :truck, :driver).references(:delivery_shift, :truck, :driver)

    if for_driver == :for_driver
      query = query.where driver: current_user
    end

    if params[:f]
      f = params[:f]

      if f[:search] && f[:search] != ''
        query = query.where('(
lower(delivery_shifts.code) like :search
or lower(delivery_shifts.name) like :search
or lower(trucks.name) like :search
or lower(users.email) like :search
)', {search: "%#{f[:search].to_s.downcase}%"})
      end
      if f[:date] && f[:date] != ''
        d = Date.strptime(f[:date], "%Y-%m-%d")
        query = query.where('trips.date BETWEEN :sd AND :ed', {sd: d, ed: d})
      end
    end

    @pagination.total_rows_count = query.count
    query = order(query, SORT, [{:f => 'trips.date', :d => 'd'}, {:f => 'trips.id', :d => 'a'}])
    @trips = query.limit(@pagination.limit).offset(@pagination.offset)
  end

  def index_my
    index :for_driver
    render 'index'
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def export_to_txt
    @trip = Trip.find(params[:id])

    text = "Routing List on #{@trip.date.strftime(ApplicationRecord.date_f)} #{@trip.time_shift.name}\r\n
    \tTruck: #{@trip.truck.name}\tDirver: #{@trip.driver.email}\r\n"

    @trip.cargo.order(:order_num).each do |c|
      delivery = c.order_delivery
      order = c.order_delivery.order
      address_client = c.order_delivery.order.address_client

      text += "\r\n
      #{c.order_num}. #{address_client.to_s_address}\r\n
Delivery: #{delivery.delivery_date_str} #{delivery.delivery_shift.name}\r\n
Order: \##{order.number} Cargo: #{delivery.handling_unit_quantity} #{delivery.handling_unit_type} (#{delivery.volume} ft3)\r\n
Contact Phone# #{address_client.phone_number} (ask: #{address_client.name})\r\n"
    end

    send_data text, :filename => "#{@trip.date.strftime('%Y-%m-%d')}_#{@trip.time_shift.code}.txt"
  end

  def export_to_pdf
    @trip = Trip.find(params[:id])
    render pdf: "#{@trip.date.strftime('%Y-%m-%d')}_#{@trip.time_shift.code}", layout: 'pdf'
  end

  def new
    @trip_params = {}
    @trip = Trip.new
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def create
    @notices = Notices.new
    @trip_params = trip_params

    unless params[:commit]
      return render 'new'
    end

    @trip = Trip.new(@trip_params)

    @notices.error "The specified date and time shift truck is not available for trip" unless Truck.available_on_date_and_time_shift(@trip.date, @trip.time_shift_code, @trip.truck_id).count == 1
    @notices.error "The specified date and time shift driver is not available for trip" unless User.available_drivers_on_date_and_time_shift(@trip.date, @trip.time_shift_code, @trip.driver_id).count == 1

    if @notices.notices.count == 0 && @trip.save
      redirect_to @trip
    else
      render 'new'
    end
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      redirect_to @trip
    else
      render 'edit'
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    redirect_to trips_path
  end


  private

  def trip_params(p = nil)
    p ||= params
    p = p.require(:trip).permit(:date, :time_shift_code, :truck_id, :driver_id)

    p
  end
end

src/LarkinDeliverySystem/app/helpers/trips_helper.rb
module TripsHelper
  def sortable(column, title = nil)
    sortable_column params, column, title, &@build_path
  end
end

src/LarkinDeliverySystem/app/views/trips/_cargo_table.html.erb
<%
  entities ||= []
%>
<div class="table-responsive">
  <%= form_tag path, :method => method do %>
      <% if can? :create, TripCargo %>
          <%= submit_tag action_button_name, class: 'btn btn-primary btn-xs' %>
          <%= submit_tag 'Save ordering', class: 'btn btn-primary btn-xs', onclick: 'save_ordering(this);', style: 'display:none;' %>
      <% end %>

      <table class="table table-bordered">

        <thead>
        <tr class="tr-s">
          <th>
            <% if can? :create, TripCargo %>
                <input type="checkbox" onclick="chek_all(this);">
            <% end %>
            №
          </th>
          <th>Volume</th>
          <th colspan="7">Origin address / Destination address</th>
        </tr>
        <tr class="tr-e">
          <th>
            Order number
          </th>
          <th>
            Unit
          </th>
          <th>
            Name
          </th>
          <th>
            Phone
          </th>
          <th>
            Address
          </th>
          <th>
            City
          </th>
          <th>
            State
          </th>
          <th>
            Zip
          </th>
          <th>
            Country
          </th>
        </tr>
        </thead>
        <tbody>
        <% entities.each do |e| %>
            <%
              if e.instance_of? TripCargo
                cargo = e
                delivery = e.order_delivery
                next unless e.order_delivery

                field_ids_name = 'cargo_ids[]'
                ids = params[:cargo_ids]
                cur_id = cargo.id
              else
                cargo = nil
                delivery = e
                field_ids_name = 'delivery_ids[]'
                ids = params[:delivery_ids]
                cur_id = delivery.id
              end

              order = delivery.order
              ids ||= []
              cur_id ||= 0
            %>

            <tr class="tr-s">
              <td>
                <% if can? :create, TripCargo %>
                    <%= check_box_tag field_ids_name, cur_id, ids.include?(cur_id.to_s), id: nil %>
                    <% if cargo %>
                        <%= cargo.order_num %>
                        <%= hidden_field_tag 'ids[]', cargo.id %>
                        <span onclick="move_up(this)"><i class="fa fa-lg fa-arrow-up" aria-hidden="true"></i></span>
                        <span onclick="move_down(this)"><i class="fa fa-lg fa-arrow-down" aria-hidden="true"></i></span>
                    <% end %>
                <% else %>
                    <%= cargo.order_num %>
                <% end %>
              </td>
              <td>
                <%= delivery.volume %>
                <% if delivery.volume %>ft<sup>3</sup>
                <% end %>
                <% if can? :create, TripCargo %>
                    <a href="<%= edit_order_order_delivery_path(order, delivery) %>">
                      <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                <% end %>
              </td>

              <td>
                <%= order.origin_address.name %>
              </td>
              <td>
                <%= order.origin_address.phone_number %>
              </td>
              <td>
                <%= order.origin_address.raw_line_1 %>
              </td>
              <td>
                <%= order.origin_address.city %>
              </td>
              <td>
                <%= order.origin_address.state %>
              </td>
              <td>
                <%= order.origin_address.zip %>
              </td>
              <td>
                <%= order.origin_address.country %>
              </td>
            </tr>
            <tr class="tr-e">
              <td>
                <a href="<%= order_path(order) %>">
                  #<%= order.number %>
                </a>
              </td>
              <td>
                <%= delivery.handling_unit_quantity %> <%= delivery.handling_unit_type %>
              </td>
              <td>
                <%= order.destination_address.name %>
              </td>
              <td>
                <%= order.destination_address.phone_number %>
              </td>
              <td>
                <%= order.destination_address.raw_line_1 %>
              </td>
              <td>
                <%= order.destination_address.city %>
              </td>
              <td>
                <%= order.destination_address.state %>
              </td>
              <td>
                <%= order.destination_address.zip %>
              </td>
              <td>
                <%= order.destination_address.country %>
              </td>
            </tr>
        <% end %>

        </tbody>
      </table>

      <% if can? :create, TripCargo %>
          <%= submit_tag action_button_name, class: 'btn btn-primary btn-xs' %>
          <%= submit_tag 'Save ordering', class: 'btn btn-primary btn-xs', onclick: 'save_ordering(this);', style: 'display:none;' %>
      <% end %>
  <% end %>
</div>

src/LarkinDeliverySystem/app/views/trips/edit.html.erb
<%= render partial: 'form', layout: 'form_wrapper', locals: {title: 'Edit trip', icon: 'fa fa-road', fullscreenBtn: true, closeBtn: true} %>

src/LarkinDeliverySystem/app/views/trips/export_to_pdf.html.erb
<h1>Routing List on <%= @trip.date.strftime(ApplicationRecord.date_f) %> <%= @trip.time_shift.name %> </h1>
<div><b>Truck:</b> <%= @trip.truck.name %> <b>Dirver:</b> <%= @trip.driver.email %></div>
<% @trip.cargo.order(:order_num).each do |c| %>
    <%
      delivery = c.order_delivery
      order = c.order_delivery.order
      address_client = c.order_delivery.order.address_client
    %>
    <div style="margin: 20px 0px;">
      <div><b><%= c.order_num %>.</b> <%= address_client.to_s_address %></div>
      <div><b>Delivery:</b> <%= delivery.delivery_date_str %> <%= delivery.delivery_shift.name %></div>
      <div><b>Order:</b> #<%= order.number %>
        <b>Cargo:</b> <%= delivery.handling_unit_quantity %> <%= delivery.handling_unit_type %> (<%= delivery.volume %>
        ft<sub>3</sub>)
      </div>
      <div><b>Contact Phone #</b> <%= address_client.phone_number %> (<b>ask:</b> <%= address_client.name %>)</div>
    </div>
<% end %>

src/LarkinDeliverySystem/app/views/trips/index.html.erb
<% content_for :ribbon do %>
    <% if can? :create, Trip %>
        <a href="<%= new_trip_path %>" class="btn btn-ribbon" rel="tooltip" data-placement="bottom">
          <i class="fa fa-plus"></i>
        </a>
    <% end %>
<% end %>

<div class="table-responsive">
  <%= render layout: 'form_wrapper', locals: {title: 'Filter trips', icon: 'fa fa-filter', collapseBtn: true, article_style: 'padding-left:0px;'} do %>
      <%= form_tag @build_path.call(params), :method => 'get', class: 'smart-form' do %>
          <%= hidden_field_tag :p, 1 %>
          <% params[:s].each do |s| %>
              <%= hidden_field_tag 's[][d]', s[:d] %>
              <%= hidden_field_tag 's[][f]', s[:f] %>
          <% end %>
          <fieldset>
            <section class="col col-6">
              <label class="label">Search</label>
              <label class="input"> <i class="icon-append fa fa-search"></i>
                <%= text_field_tag 'f[search]', (params[:f][:search] if params[:f]) %>
                <b class="tooltip tooltip-top-right"><i class="fa fa-search txt-color-teal"></i> Please enter search
                  term</b></label>
            </section>
            <section class="col col-4">
              <label class="label">Trip date</label>
              <label class="input"> <i class="icon-append fa fa-calendar"></i>
                <%= date_field_tag 'f[date]', (params[:f][:date] if params[:f]) %>
                <!--<input type="text" name="startdate" id="startdate" placeholder="Expected start date" class="hasDatepicker">-->
                <b class="tooltip tooltip-top-right"><i class="fa fa-calendar txt-color-teal"></i> Please enter date</b></label>
            </section>
            <section class="col col-2 right_section">
              <%= submit_tag 'Search', class: 'btn btn-primary' %>
            </section>
          </fieldset>
      <% end %>
  <% end %>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th>
        Trip date <%= sortable 'trips.date', 'Trip date' %>
      </th>
      <th>
        Time shift <%= sortable 'delivery_shifts.order', 'Time shift' %>
      </th>
      <th>
        Truck <%= sortable 'trucks.name', 'Truck' %>
      </th>
      <th>
        Driver <%= sortable 'users.email', 'Driver' %>
      </th>
      <th>Cargo</th>
      <th>Status</th>
    </tr>

    </thead>
    <tbody>
    <% @trips.each do |trip| %>
        <tr>
          <td>
            <a href="<%= trip_path(trip) %>">
              <%= trip.date.strftime(ApplicationRecord.date_f) if trip.date %>
            </a>

            <% if can? :export_to_txt, Trip %>
                <a href="<%= trip_txt_path(trip) %>" title="Export to txt"><i class="fa fa-lg fa-fw fa-file-text-o" aria-hidden="true"></i></a>
            <% end %>
            <% if can? :export_to_pdf, Trip %>
                <a href="<%= trip_pdf_path(trip) %>" target="_blank" title="Export to pdf"><i class="fa fa-lg fa-fw fa-file-pdf-o" aria-hidden="true"></i></a>
            <% end %>
          </td>
          <td title="<%= trip.time_shift ? trip.time_shift.name : 'delivery shift not specified' %>">
            <%= trip.time_shift_code %> - <%= trip.time_shift.name %>
          </td>
          <td>
            <%= trip.truck.name %> (<%= trip.truck.max_cubes %> ft<sup>3</sup>)
          </td>
          <td>
            <%= trip.driver.email %>
          </td>
          <td>
            <%= trip.volumes[:is_from_stock_to_client] %> ft<sup>3</sup>
            <% if trip.volumes[:is_from_client_to_stock] > 0 %>
                (return <%= trip.volumes[:is_from_client_to_stock] %> ft<sup>3</sup>)
            <% end %>
          </td>
          <th>
            Planing
          </th>
        </tr>
    <% end %>

    </tbody>
  </table>

  <%= render partial: 'pagination', locals: {pagination: @pagination} %>

</div>

src/LarkinDeliverySystem/app/views/trips/new.html.erb
<%= render partial: 'form', layout: 'form_wrapper', locals: {title: 'Planing trip', icon: 'fa fa-road', fullscreenBtn: true, closeBtn: true} %>

src/LarkinDeliverySystem/app/views/trips/show.html.erb
<% content_for :ribbon do %>
    <% if can? :export_to_txt, Trip %>
        <a href="<%= trip_txt_path(@trip) %>" class="btn btn-ribbon" rel="tooltip" data-placement="bottom" title="Export to txt"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
    <% end %>
    <% if can? :export_to_pdf, Trip %>
        <a href="<%= trip_pdf_path(@trip) %>" target="_blank" class="btn btn-ribbon" rel="tooltip" data-placement="bottom" title="Export to pdf"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
    <% end %>

    <% if can? :destroy, Trip %>
        <a href="<%= trip_path(@trip) %>" data-method="delete" class="btn btn-ribbon" rel="tooltip" data-placement="bottom"
           data-title="Delete" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! Delete?" data-html="true" data-reset-msg="Would you delete trip?">
          <i class="fa fa-remove"></i>
        </a>
    <% end %>
<% end %>



<%= render layout: 'form_wrapper', locals: {title: 'Trip', icon: 'fa fa-road', fullscreenBtn: true, closeBtn: true, article_style: 'padding-left:0px;'} do %>
    <form class="smart-form">
      <header>
        Trip and cargo
      </header>

      <%= render partial: 'notices', locals: {notices: @notices} %>

      <fieldset>
        <div class="row">
          <%= render layout: 'form_field', locals: {
              col: 'col col-6',
              field_type: :date_field, field: :date, title: 'Date', icon: 'fa fa-calendar', readonly: true, field_value: @trip.date} do %>
          <% end %>
          <%= render layout: 'form_field', locals: {
              col: 'col col-6',
              field: :time_shift, title: 'Time shift', icon: 'fa fa-clock-o', readonly: true, field_value: @trip.time_shift.name} do %>
          <% end %>
        </div>
        <div class="row">
          <%= render layout: 'form_field', locals: {
              col: 'col col-6',
              field: :truck, title: 'Truck', icon: 'fa fa-truck', readonly: true, field_value: @trip.truck.name} do %>
          <% end %>
          <%= render layout: 'form_field', locals: {
              col: 'col col-6',
              field: :driver, title: 'Driver', icon: 'fa fa-user-md', readonly: true, field_value: @trip.driver.email} do %>
          <% end %>
        </div>
      </fieldset>

    </form>
<% end %>

<div class="row">
  <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">


    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget well" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false" role="widget">
      <!-- widget options:
      usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

      data-widget-colorbutton="false"
      data-widget-editbutton="false"
      data-widget-togglebutton="false"
      data-widget-deletebutton="false"
      data-widget-fullscreenbutton="false"
      data-widget-custombutton="false"
      data-widget-collapsed="true"
      data-widget-sortable="false"

      -->
      <header role="heading">
        <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
        <h2>Default Tabs with border </h2>

        <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span></header>

      <!-- widget div-->
      <div role="content">

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
          <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->

        <!-- widget content -->
        <div class="widget-body">
          <p>
            When the orders for delivery, orders must be considered to return (to the
            <code>truck must have the necessary amount
            </code>)
          </p>
          <hr class="simple">

          <%

            cargo_items = @trip.cargo.order :order_num
            available_delivery = OrderDelivery.available_delivery_on_date_and_time_shift(@trip.date, @trip.time_shift_code)

          %>

          <ul id="myTab1" class="nav nav-tabs bordered">
            <li class="active">
              <a href="#s1" data-toggle="tab" aria-expanded="true">Cargo
                <span class="badge bg-color-blue txt-color-white"><%= cargo_items.count %></span>
                <span class="badge bg-color-blue txt-color-white">
                  <%= @trip.volumes[:is_from_stock_to_client] %> ft<sup>3</sup>
                  <% if @trip.volumes[:is_from_client_to_stock] > 0 %>
                    (return <%= @trip.volumes[:is_from_client_to_stock] %> ft<sup>3</sup>)
                <% end %> / <%= @trip.truck.max_cubes %> ft<sup>3</sup></span></a>
            </li>
            <% if can? :create, TripCargo %>
                <li class="">
                  <a href="#s2" data-toggle="tab" aria-expanded="false"><i class="fa fa-fw fa-lg fa-gear"></i> Orders
                    <span class="badge bg-color-blue txt-color-white"><%= available_delivery.count %></span>
                    <span class="badge bg-color-blue txt-color-white"><%= available_delivery.sum { |d| !Address.address_stock_names.include?(d.order.destination_address.name) ? d.volume : 0 } %>
                      ft<sup>3</sup>
                      <%
                        ret_sum = available_delivery.sum { |d| Address.address_stock_names.include?(d.order.destination_address.name) ? d.volume : 0 }
                        if ret_sum > 0 %>
                    (return <%= ret_sum %> ft<sup>3</sup>)
                <% end %>

                    </span></a>
                </li>
            <% end %>
          </ul>

          <div id="myTabContent1" class="tab-content padding-10">
            <div class="tab-pane fade active in" id="s1">
              <%= render layout: 'trips/cargo_table', locals: {entities: cargo_items, path: trip_cargo_index_path(@trip), method: 'delete', action_button_name: 'Exclude'} do %>
              <% end %>
            </div>
            <% if can? :create, TripCargo %>
                <div class="tab-pane fade" id="s2">
                  <%= render layout: 'trips/cargo_table', locals: {entities: available_delivery, path: trip_cargo_index_path(@trip), method: 'post', action_button_name: 'Include'} do %>
                  <% end %>
                </div>
            <% end %>
          </div>

        </div>
        <!-- end widget content -->

      </div>
      <!-- end widget div -->

    </div>
    <!-- end widget -->

  </article>
</div>

<script>
    function move_up(sender) {
        var tr1 = $($(sender).parents('tr')[0]);
        var tr2 = tr1.next('tr');

        var tr_pref = tr1.prev('tr').prev('tr');

        if (tr_pref.length == 1) {
            tr1.insertBefore(tr_pref);
            tr2.insertAfter(tr1);
        }

        show_save_ordering(sender);
    }

    function move_down(sender) {
        var tr1 = $($(sender).parents('tr')[0]);
        var tr2 = tr1.next('tr');

        var tr_next = tr2.next('tr').next('tr');

        if (tr_next.length == 1) {
            tr1.insertAfter(tr_next);
            tr2.insertAfter(tr1);
        }

        show_save_ordering(sender);
    }

    function show_save_ordering(sender) {
        var form = $($(sender).parents('form')[0]);
        $(form).find('input[value="Save ordering"]').each(function () {
            $(this).show();
        });
    }

    function save_ordering(sender) {
        sender.form.elements["_method"].value = 'put';
    }

    function chek_all(sender) {
        $(sender.form).find('input[type=checkbox]').each(function () {
            this.checked = sender.checked;
        });
    }

</script>