src/LarkinDeliverySystem/config/routes.rb
Rails.application.routes.draw do
  get 'trucks/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/orders/upload', to: 'orders#upload_view'
  post '/orders/upload', to: 'orders#upload'
  resources :orders, only: [:index, :show, :upload_view, :upload] do
    put '/order_deliveries/:id', to: 'order_deliveries#split'
    resources :order_deliveries, only: [:edit, :update] # знаю, знаю стоило OrderDelivery - назвать просто Delivery
  end

  get '/trips/my', to: 'trips#index_my'
  get '/trips/:id/txt', to: 'trips#export_to_txt', as: 'trip_txt'
  get '/trips/:id/pdf', to: 'trips#export_to_pdf', as: 'trip_pdf'
  resources :trips do
    put :cargo, to: 'trip_cargo#update'
    delete :cargo, to: 'trip_cargo#destroy'
    resources :cargo, :controller => :trip_cargo, only: [:create] # знаю, знаю стоило TripCargo - назвать просто Cargo
  end

  resources :trucks, only: [:index]

  devise_for :users

  root 'welcome#index'
end

src/LarkinDeliverySystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  SORT_DEST = {'a' => 'asc', 'd' => 'desc'}

  protect_from_forgery with: :exception

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  #before_action :authenticate

  protected

  def order(query, mapping, order)
    unless params[:s]
      params[:s] = order if order.instance_of? Array
      params[:s] = [order] if order.instance_of? Hash
    end

    order = params[:s].map { |s| f = s[:f]; "#{mapping[f]||f} #{SORT_DEST[s[:d]]}" }.join(',') if params[:s]
    query.order order # TODO: Убедиться что тут не может быть SQL иньекции
  end

  private

  # работает не так как нужно + часто повторно запрашивает пароль
  #USERS = { 'test@larkin.com' => '1qaz!QAZ' }
  # def authenticate
  #   authenticate_or_request_with_http_digest do |username|
  #     USERS[username]
  #   end
  # end
end

src/LarkinDeliverySystem/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def sortable_column(cur_params, column, title, &url)
    title ||= column.titleize
    original_sort_arr = cur_params[:s] || []

    index = original_sort_arr.index { |x| x[:f] == column }
    direction = 'a'
    if index && index >= 0
      s = original_sort_arr[index]
      direction = s[:d] == 'd' ? 'a' : 'd'
      sort_order = index + 1
      asc = s[:d] == 'a'
      desc = s[:d] == 'd'
    end

    sort_arr = []
    sort_arr << {:f => column, :d => direction}
    original_sort_arr.each { |s| sort_arr << {:f => s[:f], :d => s[:d]} if s[:f] != column }

    url = url.call(cur_params.merge(:s => sort_arr))

    render partial: 'sortable_column', locals: {title: title, url: url, sort_order: sort_order, asc: asc, desc: desc}
  end
end

src/LarkinDeliverySystem/app/views/application/_form_field.erb
<%
  f ||= nil
  readonly ||= false
  col ||= ''
  field_type ||= nil
  field ||= nil
  field_value ||= nil
  title ||= nil
  icon ||= ''
  tooltip ||= "Please enter #{ title || field || 'field'}" unless readonly
  tooltip ||= "#{ title || field || 'field'}" if readonly
  lab_wr_cl ||= 'input'
  required ||= false
  auto_submit ||= false
%>
<section class="<%= col %>">
  <% if f %>
      <%= f.label field, title, class: 'label' %>
  <% else %>
      <%= label_tag field, title, class: 'label' %>
  <% end %>
  <label class="<%= lab_wr_cl %>">
    <% if icon %>
        <i class="icon-append <%= icon %>"></i>
    <% end %>
    <%= yield %>
    <% unless readonly %>
        <% case field_type
             when :date_field %>
            <%= f.date_field field, required: required, onchange: auto_submit ? 'this.form.submit();' : nil if f %>
            <%= date_field_tag field, field_value unless f %>
        <% end %>
    <% else %>
        <% case field_type
             when :date_field %>
            <%= f.date_field field, readonly: true if f %>
            <%= date_field_tag field, field_value ? field_value.strftime("%Y-%m-%d") : nil, readonly: true unless f %>
        <% else %>
            <%= f.text_field field, readonly: true if f %>
            <%= text_field_tag field, field_value, readonly: true unless f %>
        <% end %>
    <% end %>
    <% if icon && icon != '' %>
        <b class="tooltip tooltip-top-right">
          <i class="<%= icon %> txt-color-teal"></i>
          <%= tooltip %>
        </b>
    <% end %>
  </label>
</section>

src/LarkinDeliverySystem/app/views/application/_form_wrapper.html.erb
<%
  article_style ||= ''
  collapseBtn ||= false
  fullscreenBtn ||= false
  closeBtn ||= false
  icon ||= ''
  title ||= '???'
%>
<article class="col-sm-12 col-md-12 col-lg-6 sortable-grid ui-sortable" style="<%= article_style ? article_style : '' %>">

  <!-- Widget ID (each widget will need unique ID)-->
  <div class="jarviswidget jarviswidget-sortable" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false" role="widget">
    <!-- widget options:
    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

    data-widget-colorbutton="false"
    data-widget-editbutton="false"
    data-widget-togglebutton="false"
    data-widget-deletebutton="false"
    data-widget-fullscreenbutton="false"
    data-widget-custombutton="false"
    data-widget-collapsed="true"
    data-widget-sortable="false"

    -->
    <header role="heading">
      <div class="jarviswidget-ctrls" role="menu">
        <% if collapseBtn %>
            <a href="javascript:void(0);" class="button-icon jarviswidget-toggle-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Collapse"><i class="fa fa-minus "></i></a>
        <% end %>
        <% if fullscreenBtn %>
            <a href="javascript:void(0);" class="button-icon jarviswidget-fullscreen-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Fullscreen"><i class="fa fa-expand "></i></a>
        <% end %>
        <% if closeBtn %>
            <a href="javascript:void(0);" class="button-icon jarviswidget-delete-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Close"><i class="fa fa-times"></i></a>
        <% end %>
      </div>
      <span class="widget-icon"> <i class="<%= icon %>"></i> </span>
      <h2><%= title %></h2>

      <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
    </header>

    <!-- widget div-->
    <div role="content">

      <!-- widget edit box -->
      <div class="jarviswidget-editbox">
        <!-- This area used as dropdown edit box -->

      </div>
      <!-- end widget edit box -->

      <!-- widget content -->
      <div class="widget-body no-padding">
        <%= yield %>
      </div>
      <!-- end widget content -->

    </div>
    <!-- end widget div -->

  </div>
  <!-- end widget -->

</article>

src/LarkinDeliverySystem/app/views/application/_left_panel.html.erb
<!-- #NAVIGATION -->
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS/SASS variables -->

<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as is -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
						<img src="/img/avatars/sunny.png" alt="me" class="online"/>
						<span>
							<%= current_user.email %>
						</span>
						<i class="fa fa-angle-down"></i>
					</a>

				</span>
  </div>
  <!-- end user info -->

  <!-- NAVIGATION : This navigation is also responsive

  To make this navigation dynamic please make sure to link the node
  (the reference to the nav > ul) after page load. Or the navigation
  will not initialize.
  -->
  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->

    <ul>
      <li class="">
        <a href="/" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i>
          <span class="menu-item-parent">Dashboard</span></a>
      </li>

      <% if can? :index, Order %>
          <li class="">
            <a href="#" title="Orders"><i class="fa fa-lg fa-fw fa-truck"></i>
              <span class="menu-item-parent">Orders</span></a>
            <ul>
              <li class="">
                <a href="<%= orders_path %>" title="All orders"><span class="menu-item-parent">All orders</span></a>
              </li>
              <% if can? :upload, Order %>
                  <li class="">
                    <a href="<%= orders_upload_path %>" title="Upload"><span class="menu-item-parent">Upload</span></a>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>

      <% if can?(:index, Trip) || can?(:index_my, Trip) %>
          <li class="">
            <a href="#" title="Trips"><i class="fa fa-lg fa-fw fa-road"></i>
              <span class="menu-item-parent">Trips</span></a>
            <ul>
              <% if can? :index, Trip %>
                  <li class="">
                    <a href="<%= trips_path %>" title="All trips"><span class="menu-item-parent">All trips</span></a>
                  </li>
              <% end %>
              <% if can? :index_my, Trip %>
                  <li class="">
                    <a href="<%= trips_my_path %>" title="My trips"><span class="menu-item-parent">My trips</span></a>
                  </li>
              <% end %>
              <% if can? :create, Trip %>
                  <li class="">
                    <a href="<%= new_trip_path %>" title="Planing trip"><span class="menu-item-parent">Planing trip</span></a>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>

      <% if can? :index, Truck %>
          <li class="">
            <a href="#" title="Reference"><i class="fa fa-lg fa-fw fa-table"></i>
              <span class="menu-item-parent">Reference</span></a>
            <ul>
              <% if can? :index, Truck %>
                  <li class="">
                    <a href="<%= trucks_path %>" title="Trucks"><span class="menu-item-parent">Trucks</span></a>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>
    </ul>
  </nav>

  <span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>

</aside>

<!-- END NAVIGATION -->

src/LarkinDeliverySystem/app/views/application/_notices.html.erb
<% if notices %>
    <article class="col-sm-12">
      <% notices.notices.each do |notice| %>

          <% case notice.type
               when Notice::SUCCESS %>
              <div class="alert alert-success fade in">
                <button class="close" data-dismiss="alert">×</button>
                <i class="fa-fw fa fa-check"></i>
                <strong>Success</strong> <%= notice.message %>
              </div>

          <% when Notice::INFO %>
              <div class="alert alert-info fade in">
                <button class="close" data-dismiss="alert">×</button>
                <i class="fa-fw fa fa-info"></i>
                <strong>Info!</strong> <%= notice.message %>
              </div>

          <% when Notice::WARNING %>
              <div class="alert alert-warning fade in">
                <button class="close" data-dismiss="alert">×</button>
                <i class="fa-fw fa fa-warning"></i>
                <strong>Warning</strong> <%= notice.message %>
              </div>

          <% when Notice::ERROR %>
              <div class="alert alert-danger fade in">
                <button class="close" data-dismiss="alert">×</button>
                <i class="fa-fw fa fa-times"></i>
                <strong>Error!</strong> <%= notice.message %>
              </div>

          <% end %>

      <% end %>
    </article>
<% end %>

src/LarkinDeliverySystem/app/views/application/_pagination.html.erb
<ul class="pagination">
  <% pagination.buttons.each do |b| %>
      <li class="<%= 'active' if b.is_active %>"><a href="<%= b.url %>"><%= b.name %></a></li>
  <% end %>
</ul>

src/LarkinDeliverySystem/app/views/application/_sortable_column.html.erb
<div class="sortable_column">
  <%
    icon = 'fa fa-sort'
    icon = 'fa fa-sort-alpha-asc' if sort_order && asc
    icon = 'fa fa-sort-alpha-desc' if sort_order && desc
  %>
  <!--<a href="<%= url %>"><%= title %></a>-->
  <a href="<%= url %>" title="<%= "sort #{asc ? 'descending' : 'ascending'} by  #{title}" %>">
    <i style="<%= 'color: silver' unless sort_order %>" class="<%= icon %>"></i>
    <% if sort_order %><sup><%= sort_order %></sup>
    <% end %>
  </a>
</div>