src/LarkinDeliverySystem/config/routes.rb
Rails.application.routes.draw do
  get 'trucks/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/orders/upload', to: 'orders#upload_view'
  post '/orders/upload', to: 'orders#upload'
  resources :orders, only: [:index, :show, :upload_view, :upload] do
    put '/order_deliveries/:id', to: 'order_deliveries#split'
    resources :order_deliveries, only: [:edit, :update] # знаю, знаю стоило OrderDelivery - назвать просто Delivery
  end

  get '/trips/my', to: 'trips#index_my'
  get '/trips/:id/txt', to: 'trips#export_to_txt', as: 'trip_txt'
  get '/trips/:id/pdf', to: 'trips#export_to_pdf', as: 'trip_pdf'
  resources :trips do
    put :cargo, to: 'trip_cargo#update'
    delete :cargo, to: 'trip_cargo#destroy'
    resources :cargo, :controller => :trip_cargo, only: [:create] # знаю, знаю стоило TripCargo - назвать просто Cargo
  end

  resources :trucks, only: [:index]

  devise_for :users

  root 'welcome#index'
end

src/LarkinDeliverySystem/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :origin_address, :class_name => 'Address', :foreign_key => 'origin_address_id', :validate => true
  belongs_to :destination_address, :class_name => 'Address', :foreign_key => 'destination_address_id', :validate => true

  has_many :deliveries, :class_name => 'OrderDelivery'

  def next_delivery_date
    self['next_delivery_date']
  end

  def last_delivered_date
    self['last_delivered_date']
  end

  def is_from_client_to_stock
    # признак возврата
    #is_from_stock_to_client = Address.address_stock_names.include?(origin_address.name) # доставка
    is_from_client_to_stock = Address.address_stock_names.include?(destination_address.name) # возврат
    is_from_client_to_stock
  end

  def is_from_stock_to_client
    # признак доставки
    !is_from_client_to_stock # если не возврат то доставка
  end

  def address_client
    # вернет адресс клиента, куда нужно доставить или забрать груз
    return origin_address if is_from_client_to_stock
    # !is_from_stock_to_client && !is_from_client_to_stock "У заказа в адресах не указан склад, по этому он будет считаться доставкой клиенту (а не возвратом)"
    return destination_address
  end
end

src/LarkinDeliverySystem/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  require 'csv'

  SORT = {
      'next_delivery_date_or_last_delivered_date' => 'coalesce(d42.next_delivery_date_not_specified, coalesce(d42.next_delivery_date, coalesce(d42.last_delivered_date, \'1914-12-25\')))',
      'o_name' => 'addresses.name', # addresses - это Active Record так alias объвляет
      'd_name' => 'destination_addresses_orders.name', # destination_addresses_orders - это Active Record так alias объвляет
      'o_phone' => 'addresses.phone_number',
      'd_phone' => 'destination_addresses_orders.phone_number',
      'o_address' => 'addresses.raw_line_1',
      'd_address' => 'destination_addresses_orders.raw_line_1',
      'o_city' => 'addresses.city',
      'd_city' => 'destination_addresses_orders.city',
      'o_state' => 'addresses.state',
      'd_state' => 'destination_addresses_orders.state',
      'o_zip' => 'addresses.zip',
      'd_zip' => 'destination_addresses_orders.zip',
      'o_country' => 'addresses.country',
      'd_country' => 'destination_addresses_orders.country'
  }

  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @build_path = lambda { |p| orders_path(p.permit(:p, s: [:f, :d], f: [:utf8, :search, :date, :state, :direct, :commit])) }

    @pagination = Pagination.new(params, :p, 10, 20, &@build_path)

    query = Order.joins(:origin_address, :destination_address)
                .joins('
left outer join
(
  select
    d47.order_id
    ,min
    (
      case
        when tc.order_delivery_id is null then d47.delivery_date
        else null
      end
    ) as next_delivery_date -- самая первая дата доставки (если еще не доставлено)
    ,min
    (
      case
        when tc.order_delivery_id is null and d47.delivery_date is null then coalesce(d47.delivery_date, \'1983-11-10\')
        else null
      end
    ) as next_delivery_date_not_specified -- самая плохая дата доставки, так как не указана
    ,max
    (
      case
        when tc.order_delivery_id is not null then d47.delivery_date
        else null
      end
    ) as last_delivered_date -- дата последней доставки (или запланированной доставки (имется в виду, что включено в груз) - так как процесс дальше планирования не распространияется)
    ,max
    (
      case
        when d47.delivery_date is null or d47.delivery_shift_code is null then 1
        else 0
      end
    ) as invalid -- что то не указано
    ,min
    (
      case
        when tc.order_delivery_id is null then 0
        else 1
      end
    ) as not_planed -- есть не запланированные
    ,min
    (
      case
        when tc.order_delivery_id is null and not (d47.delivery_date is null or d47.delivery_shift_code is null) then 0
        else 1
      end
    ) as not_planed_only_valid -- есть не запланированные, без учета не корректных
    ,max
    (
      case
        when tc.order_delivery_id is not null then 1
        else 0
      end
    ) as planed -- есть запланированные
    ,min
    (
      case
        when tc.order_delivery_id is not null then 1
        else 0
      end
    ) as full_planed -- полностью запланированны
  from order_deliveries as d47
    left join trip_cargos tc on tc.order_delivery_id = d47.id
  group by d47.order_id
) as d42 on d42.order_id = orders.id')
    query = query.references(:origin_address, :destination_address)

    if params[:f]
      f = params[:f]

      if f[:search] && f[:search] != ''
        query = query.where('(
orders.number like :search
or lower(addresses.name) like :search or lower(destination_addresses_orders.name) like :search
or lower(addresses.phone_number) like :search or lower(destination_addresses_orders.phone_number) like :search
or lower(addresses.raw_line_1) like :search or lower(destination_addresses_orders.raw_line_1) like :search
or lower(addresses.city) like :search or lower(destination_addresses_orders.city) like :search
or lower(addresses.state) like :search or lower(destination_addresses_orders.state) like :search
or lower(addresses.zip) like :search or lower(destination_addresses_orders.zip) like :search
or lower(addresses.country) like :search or lower(destination_addresses_orders.country) like :search
)', {search: "%#{f[:search].to_s.downcase}%"})
      end

      if f[:date] != ''
        d = Date.strptime(f[:date], "%Y-%m-%d")
        query = query.where('exists(select 1 from order_deliveries as d47_2 where d47_2.delivery_date BETWEEN :sd AND :ed and d47_2.order_id = orders.id)', {sd: d, ed: d})
      end

      if f[:state] == 'invalid'
        query = query.where('d42.invalid = 1')
      elsif f[:state] == 'not_planed'
        query = query.where('d42.not_planed = 0')
      elsif f[:state] == 'not_planed_only_valid'
        query = query.where('d42.not_planed_only_valid = 0')
      elsif f[:state] == 'planed'
        query = query.where('d42.planed = 1')
      elsif f[:state] == 'full_planed'
        query = query.where('d42.full_planed = 1')
      end

      if f[:direct] == 'from_stock'
        query = query.where("addresses.name in (#{Address.address_stock_names_to_s_sql})")
      elsif f[:direct] == 'to_stock'
        query = query.where("destination_addresses_orders.name in (#{Address.address_stock_names_to_s_sql})")
      end
    end

    @pagination.total_rows_count = query.count

    query = query.select('d42.next_delivery_date, d42.next_delivery_date_not_specified, d42.last_delivered_date, orders.*') #orders.* - фикс ActiveRecords, генерит кривой sql и потом еще не может найти поля
    query = order(query, SORT, [{:f => 'next_delivery_date_or_last_delivered_date', :d => 'a'}, {:f => 'orders.id', :d => 'a'}])
    @orders = query.limit(@pagination.limit).offset(@pagination.offset)
  end

  def show
    @order = Order.includes(:origin_address, :destination_address).find params[:id]
  end

  def upload_view
    params[:not_download_all] = 'not_download_all'
  end

  def upload
    @notices = Notices.new

    begin
      fields = ['delivery_date', 'delivery_shift', 'origin_name', 'origin_raw_line_1', 'origin_city', 'origin_state',
                'origin_zip', 'origin_country', 'client name', 'destination_raw_line_1', 'destination_city',
                'destination_state', 'destination_zip', 'destination_country', 'phone_number', 'mode',
                'purchase_order_number', 'volume', 'handling_unit_quantity', 'handling_unit_type']

      uploaded_io = params[:file]

      if uploaded_io.nil?
        raise 'Unknown file'
      end

      if File.extname(uploaded_io.original_filename) != '.csv'
        raise 'File extension must be csv'
      end

      csv_text = uploaded_io.read()
      csv = CSV.parse(csv_text, :headers => true)

      not_found_fields = fields - csv.headers
      if not_found_fields != []
        raise 'File format is not valid. Not found columns: ' + not_found_fields.map(&:inspect).join(', ')
      end

      rollback = false
      Order.transaction do
        csv.each_with_index do |row, row_index|
          row_line = row_index + 2
          # TODO: Добавить предварительную валидацию полей (или на основе модели валидации ActiveRecords), и сохранение с пропуском не валидных полей

          unless row['purchase_order_number']
            @notices.warning "In line #{row_line} not specified order number - record missing" unless params[:not_download_all] == 'not_download_all'
            raise "In line #{row_line} not specified order number" if params[:not_download_all] == 'not_download_all'
            next
          end

          order = Order.find_by number: row['purchase_order_number']
          order = order || Order.new #create!(row.to_hash)

          if order.new_record?
            order.number = row['purchase_order_number']
          end

          fill_addresses(order, row)

          order.save! if params[:not_download_all] == 'not_download_all'
          unless params[:not_download_all] == 'not_download_all'
            if !order.save
              @notices.warning "In line #{row_line} error save - record missing (#{order.errors.full_messages.join(',')})"
              next
            end
          end

          #9/15/2014
          delivery_date = nil
          if row['delivery_date']
            delivery_date = Date.strptime(row['delivery_date'], ApplicationRecord.date_f)
          end

          original_key = "d_#{row['delivery_date']}_s_#{row['delivery_shift']}_m_#{row['mode']}"+
              "_v_#{row['volume']}_uq_#{row['handling_unit_quantity']}_ut_#{row['handling_unit_type']}"

          delivery = order.deliveries.find_by original_key: original_key
          delivery = delivery || order.deliveries.new
          if delivery.new_record?
            delivery.original_key = original_key
            delivery.delivery_date = delivery_date
            delivery.delivery_shift_code = row['delivery_shift']
            delivery.mode = row['mode']
            delivery.volume = row['volume']
            delivery.handling_unit_quantity = row['handling_unit_quantity']
            delivery.handling_unit_type = row['handling_unit_type']
          else
            msg = "In line #{row_line} is already loaded"
            raise msg if params[:not_download_all] == 'not_download_all'
            unless params[:not_download_all] == 'not_download_all'
              @notices.warning "#{msg} - record missing"
              next
            end
          end

          order.save! if params[:not_download_all] == 'not_download_all'
          unless params[:not_download_all] == 'not_download_all'
            if !order.save
              @notices.warning "In line #{row_line} error save - record missing (#{order.errors.full_messages.join(',')})"
              next
            end
          end
        end

        if rollback && params[:not_download_all] == 'not_download_all'
          ActiveRecord::Rollback
          raise "Download canceled"
        end
      end

      @notices.success 'successfully'
      return render 'uploaded'

    rescue => error

src/LarkinDeliverySystem/app/helpers/order_helper.rb
module OrderHelper
  def sortable(column, title = nil)
    sortable_column params, column, title, &@build_path
  end
end

src/LarkinDeliverySystem/app/views/orders/_address.html.erb
<%
  address ||= nil
  prefix ||= 'address'
  title ||= ''

  return unless address
%>
<fieldset>
  <div class="row">
    <section>
      <div class="col col-12">
        <%= title %>
      </div>
    </section>
  </div>
  <div class="row">
    <%= render layout: 'form_field', locals: {
        col: 'col col-6',
        field: "#{prefix}_name", title: 'Name', icon: 'fa fa-user', readonly: true, field_value: address.name} do %>
    <% end %>
    <%= render layout: 'form_field', locals: {
        col: 'col col-6',
        field: "#{prefix}_phone", title: 'Phone', icon: 'fa fa-phone', readonly: true, field_value: address.phone_number} do %>
    <% end %>
  </div>
  <div class="row">
    <%= render layout: 'form_field', locals: {
        col: 'col col-6',
        field: "#{prefix}_raw_line_1", title: 'Address', icon: 'fa fa-map-marker', readonly: true, field_value: address.raw_line_1} do %>
    <% end %>
    <%= render layout: 'form_field', locals: {
        col: 'col col-6',
        field: "#{prefix}_city", title: 'City', icon: 'fa fa-map-marker', readonly: true, field_value: address.city} do %>
    <% end %>
  </div>
  <div class="row">
    <%= render layout: 'form_field', locals: {
        col: 'col col-4',
        field: "#{prefix}_state", title: 'State', icon: 'fa  fa-map-marker', readonly: true, field_value: address.state} do %>
    <% end %>
    <%= render layout: 'form_field', locals: {
        col: 'col col-4',
        field: "#{prefix}_zip", title: 'Zip', icon: 'fa  fa-map-marker', readonly: true, field_value: address.zip} do %>
    <% end %>
    <%= render layout: 'form_field', locals: {
        col: 'col col-4',
        field: "#{prefix}_country", title: 'Country', icon: 'fa fa-globe', readonly: true, field_value: address.country} do %>
    <% end %>
  </div>
</fieldset>

src/LarkinDeliverySystem/app/views/orders/_order.html.erb
<%= render layout: 'form_wrapper', locals: {title: 'Order', icon: 'fa fa-road', fullscreenBtn: true, closeBtn: true, article_style: 'padding-left:0px;'} do %>
    <form class="smart-form">
      <header>
        Order and deliveries
      </header>

      <%= render partial: 'notices', locals: {notices: @notices} %>

      <fieldset>
        <div class="row">
          <%= render layout: 'form_field', locals: {
              col: 'col col-6',
              field: :time_shift, title: 'Order #', icon: 'fa fa-shopping-cart', readonly: true, field_value: @order.number} do %>
          <% end %>
        </div>

      </fieldset>

      <%= render 'orders/address', address: @order.origin_address, prefix: 'origin_address', title: 'Origin' %>
      <%= render 'orders/address', address: @order.destination_address, prefix: 'destination_address', title: 'Destination' %>
    </form>
<% end %>

src/LarkinDeliverySystem/app/views/orders/index.html.erb
<% content_for :ribbon do %>
    <a href="<%= orders_upload_path %>" class="btn btn-ribbon" rel="tooltip" data-placement="bottom">
      <i class="fa fa-upload"></i>
    </a>
<% end %>

<div class="table-responsive">

  <%= render layout: 'form_wrapper', locals: {title: 'Filter orders', icon: 'fa fa-filter', collapseBtn: true, article_style: 'padding-left:0px;'} do %>
      <%= form_tag orders_path(@params), :method => 'get', class: 'smart-form' do %>
          <%= hidden_field_tag :p, 1 %>
          <% params[:s].each do |s| %>
              <%= hidden_field_tag 's[][d]', s[:d] %>
              <%= hidden_field_tag 's[][f]', s[:f] %>
          <% end %>
          <fieldset>
            <div class="row">
              <section class="col col-6">
                <label class="label">Search</label>
                <label class="input"> <i class="icon-append fa fa-search"></i>
                  <%= text_field_tag 'f[search]', (params[:f][:search] if params[:f]) %>
                  <b class="tooltip tooltip-top-right"><i class="fa fa-search txt-color-teal"></i> Please enter search
                    term</b></label>
              </section>
              <section class="col col-3">
                <label class="label">Date</label>
                <label class="input"> <i class="icon-append fa fa-calendar"></i>
                  <%= date_field_tag 'f[date]', (params[:f][:date] if params[:f]) %>
                  <!--<input type="text" name="startdate" id="startdate" placeholder="Expected start date" class="hasDatepicker">-->
                  <b class="tooltip tooltip-top-right"><i class="fa fa-calendar txt-color-teal"></i> Please enter
                    date</b></label>
              </section>
            </div>
            <div class="row">
              <section class="col col-3">
              </section>
              <section class="col col-3">
                <label class="label">State</label>
                <label class="select">
                  <select name="f[state]">
                    <% # знаю о специальных хелперах...
                       v = params[:f] && params[:f][:state] ? params[:f][:state] : nil
                    %>
                    <option value="all" <%= 'selected' if v.nil? || v == 'all' %> >All</option>
                    <option value="invalid" <%= 'selected' if v == 'invalid' %> >Invalid</option>
                    <option value="not_planed" <%= 'selected' if v == 'not_planed' %> >Not planed</option>
                    <option value="not_planed_only_valid" <%= 'selected' if v == 'not_planed_only_valid' %> >Not planed
                      (only valid)
                    </option>
                    <option value="planed" <%= 'selected' if v == 'planed' %> >Exists planed</option>
                    <option value="full_planed" <%= 'selected' if v == 'full_planed' %> >Full planed</option>
                  </select> <i></i> </label>
              </section>
              <section class="col col-3">
                <label class="label">Direction</label>
                <label class="select">
                  <select name="f[direct]">
                    <% # знаю о специальных хелперах...
                       v = params[:f] && params[:f][:direct] ? params[:f][:direct] : nil
                    %>
                    <option value="any" <%= 'selected' if v.nil? || v == 'any' %> >Any</option>
                    <option value="from_stock" <%= 'selected' if v == 'from_stock' %> >From stock</option>
                    <option value="to_stock" <%= 'selected' if v == 'to_stock' %> >To stock</option>
                  </select> <i></i> </label>
              </section>
              <section class="col col-3 right_section">
                <%= submit_tag 'Search', class: 'btn btn-primary' %>
              </section>
            </div>
          </fieldset>
      <% end %>
  <% end %>

  <table class="table table-bordered">
    <thead>
    <tr class="tr-s">
      <th style="width: 140px;">
        <span style="color: #9a0325;">Next delivery</span> (<span style="color: #0aa66e;">or last delivered</span>)
        date <%= sortable 'next_delivery_date_or_last_delivered_date', 'Next delivery date' %>
      </th>
      <th>Deliveries</th>
      <th colspan="7">Origin address / Destination address</th>
    </tr>
    <tr class="tr-e">
      <th>
        Order number <%= sortable 'number', 'Order number' %>
      </th>
      <th>
        <div class="row">
          <div class="col-md-1">
          </div>
          <div class="col-md-1" title="Status">
            <i class="fa fa-lg fa-fw fa-road" aria-hidden="true"></i>
          </div>
          <div class="col-md-1">
            Mode
          </div>
          <div class="col-md-3">
            Date
          </div>
          <div class="col-md-1">
            Shift
          </div>
          <div class="col-md-3">
            Volume
          </div>
          <div class="col-md-2">
            Unit
          </div>
        </div>
      </th>
      <th>
        Name
        <div class="sortable_columns">
          <%= sortable 'o_name', 'Origin name' %> / <%= sortable 'd_name', 'Client name' %>
        </div>
      </th>
      <th>
        Phone
        <div class="sortable_columns">
          <%= sortable 'o_phone', 'Origin phone' %> / <%= sortable 'd_phone', 'Destination phone' %>
        </div>
      </th>
      <th>
        Address
        <div class="sortable_columns">
          <%= sortable 'o_address', 'Origin address' %> / <%= sortable 'd_address', 'Destination address' %>
        </div>
      </th>
      <th>
        City
        <div class="sortable_columns">
          <%= sortable 'o_city', 'Origin city' %> / <%= sortable 'd_city', 'Destination city' %>
        </div>
      </th>
      <th>
        State
        <div class="sortable_columns">
          <%= sortable 'o_state', 'Origin state' %> / <%= sortable 'd_state', 'Destination state' %>
        </div>
      </th>
      <th>
        Zip
        <div class="sortable_columns">
          <%= sortable 'o_zip', 'Origin zip' %> / <%= sortable 'd_zip', 'Destination zip' %>
        </div>
      </th>
      <th>
        Country
        <div class="sortable_columns">
          <%= sortable 'o_country', 'Origin country' %> / <%= sortable 'd_country', 'Destination zip' %>
        </div>
      </th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
        <tr class="tr-s">
          <td>
            <span style="color: #9a0325;"><%= order.next_delivery_date.strftime(ApplicationRecord.date_f) if order.next_delivery_date %></span>
            <span style="color: #0aa66e;"><%= order.last_delivered_date.strftime(ApplicationRecord.date_f) if order.last_delivered_date %></span>
          </td>
          <td rowspan="2">
            <% order.deliveries.order(:delivery_date).each do |delivery| %>
                <div class="row">
                  <div class="col-md-1">
                    <a href="<%= edit_order_order_delivery_path(order, delivery) %>" title="Edit delivery">
                      <i class="fa fa-lg fa-fw fa-pencil" aria-hidden="true"></i>
                    </a>
                  </div>
                  <%
                    status = 'Not planed'
                    status_color = 'black'
                    if !delivery.trip_cargo.nil?
                      status = 'Planed trip'
                      status_color = '#0aa66e'
                    elsif delivery.invalid
                      status = "Invalid: #{delivery.invalid_message}"
                      status_color = 'red'
                    end

                  %>
                  <div class="col-md-1" title="<%= status %>">
                    <% if !delivery.trip_cargo.nil? %>
                        <a href="<%= trip_path(delivery.trip_cargo.trip_id) %>" style="color: <%= status_color %>;">
                          <i style="color: <%= status_color %>;" class="fa fa-lg fa-fw fa-road" aria-hidden="true"></i>
                        </a>
                    <% else %>
                        <span style="color: <%= status_color %>;"><i class="fa fa-lg fa-fw fa-ban" aria-hidden="true"></i></span>
                    <% end %>
                  </div>
                  <div class="col-md-1" title="<%= delivery.mode %>">
                    <i style="color: <%= status_color %>;" class="fa fa-lg fa-fw <%= delivery.mode == "TRUCKLOAD" ? 'fa-truck' : 'fa-question-circle-o' %>"></i>
                  </div>
                  <div class="col-md-3" title="<%= 'delivery date not specified' unless delivery.delivery_date %>">
                    <%= delivery.delivery_date_str if delivery.delivery_date %>
                    <% unless delivery.delivery_date %>
                        <i style="color: red;" class="fa fa-lg fa-fw fa-question-circle-o"></i>
                    <% end %>
                  </div>
                  <div class="col-md-1" title="<%= delivery.delivery_shift ? delivery.delivery_shift.name : 'delivery shift not specified' %>">
                    <%= delivery.delivery_shift_code %>
                    <% unless delivery.delivery_shift_code %>
                        <i style="color: red;" class="fa fa-lg fa-fw fa-question-circle"></i>
                    <% end %>
                  </div>
                  <div class="col-md-3">
                    <%= delivery.volume %>
                    <% if delivery.volume %>ft<sup>3</sup>
                    <% end %>
                  </div>
                  <div class="col-md-2">
                    <%= delivery.handling_unit_quantity %> <%= delivery.handling_unit_type %>
                  </div>
                </div>
            <% end %>
          </td>
          <td>
            <%= order.origin_address.name %>
          </td>
          <td>
            <%= order.origin_address.phone_number %>
          </td>
          <td>
            <%= order.origin_address.raw_line_1 %>
          </td>
          <td>
            <%= order.origin_address.city %>
          </td>
          <td>
            <%= order.origin_address.state %>
          </td>
          <td>
            <%= order.origin_address.zip %>
          </td>
          <td>
            <%= order.origin_address.country %>
          </td>
        </tr>
        <tr class="tr-e">
          <td>
            <a href="<%= order_path(order) %>">
              #<%= order.number %>
            </a>
          </td>
          <td>
            <%= order.destination_address.name %>
          </td>
          <td>
            <%= order.destination_address.phone_number %>
          </td>
          <td>
            <%= order.destination_address.raw_line_1 %>
          </td>
          <td>
            <%= order.destination_address.city %>
          </td>
          <td>
            <%= order.destination_address.state %>
          </td>
          <td>
            <%= order.destination_address.zip %>
          </td>
          <td>
            <%= order.destination_address.country %>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>

  <%= render partial: 'pagination', locals: {pagination: @pagination} %>

</div>

src/LarkinDeliverySystem/app/views/orders/index_datagrid.html.erb
<%= datagrid_form_for @orders_grid, url: orders_url %>
<div class='total'>Total: <%= @orders_grid.assets.total_count %></div>
<%= datagrid_table(@orders_grid) %>
<%= paginate @orders_grid.assets %>

src/LarkinDeliverySystem/app/views/orders/show.html.erb
<% content_for :ribbon do %>
<% end %>

<%= render 'order' %>

<%= render layout: 'form_wrapper', locals: {title: 'Deliveries', icon: 'fa fa-road', fullscreenBtn: true, closeBtn: true, article_style: 'padding-left:0px;'} do %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th style="width: 50px;"></th>
          <th style="width: 50px;" title="Status">
            <i class="fa fa-lg fa-fw fa-road" aria-hidden="true"></i></th>
          <th>Mode</th>
          <th>Date</th>
          <th>Shift</th>
          <th>Volume</th>
          <th>Unit</th>
        </tr>
        </thead>
        <tbody>
        <% @order.deliveries.order(:delivery_date).each do |delivery| %>
            <% order = @order %>
            <tr>
              <td>
                <a href="<%= edit_order_order_delivery_path(order, delivery) %>" title="Edit delivery">
                  <i class="fa fa-lg fa-fw fa-pencil" aria-hidden="true"></i>
                </a>
              </td>
              <%
                status = 'Not planed'
                status_color = 'black'
                if !delivery.trip_cargo.nil?
                  status = 'Planed trip'
                  status_color = '#0aa66'
                elsif delivery.invalid
                  status = "Invalid: #{delivery.invalid_message}"
                  status_color = 'red'
                end
              %>
              <td title="<%= status %>">
                <% if !delivery.trip_cargo.nil? %>
                    <a href="<%= trip_path(delivery.trip_cargo.trip_id) %>" style="color: <%= status_color %>">
                      <i class="fa fa-lg fa-fw fa-road" aria-hidden="true"></i>
                    </a>
                <% else %>
                    <span style="color: <%= status_color %>"><i class="fa fa-lg fa-fw fa-road" aria-hidden="true"></i></span>
                <% end %>
              </td>
              <td title="<%= delivery.mode %>">
                <i class="fa fa-lg fa-fw <%= delivery.mode == "TRUCKLOAD" ? 'fa-truck' : 'fa-question-circle-o' %>"></i>
              </td>
              <td title="<%= 'delivery date not specified' unless delivery.delivery_date %>">
                <%= delivery.delivery_date_str if delivery.delivery_date %>
                <% unless delivery.delivery_date %>
                    <i style="color: red;" class="fa fa-lg fa-fw fa-question-circle-o"></i>
                <% end %>
              </td>
              <td title="<%= delivery.delivery_shift ? delivery.delivery_shift.name : 'delivery shift not specified' %>">
                <%= delivery.delivery_shift_code %>
                <% unless delivery.delivery_shift_code %>
                    <i style="color: red;" class="fa fa-lg fa-fw fa-question-circle"></i>
                <% end %>
              </td>
              <td>
                <%= delivery.volume %>
                <% if delivery.volume %>ft<sup>3</sup>
                <% end %>
              </td>
              <td>
                <%= delivery.handling_unit_quantity %> <%= delivery.handling_unit_type %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>